---
apiVersion: v2
appVersion: 2023.12.2
description: Open-source API development ecosystem
name: hoppscotch
version: 1.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - hoppscotch
home: https://github.com/homelab-ci/ezUxewsl/tree/master/charts/stable/hoppscotch
icon: https://mintlify.s3-us-west-1.amazonaws.com/hoppscotch/logo/dark.svg
sources:
  - https://github.com/hoppscotch/hoppscotch
maintainers:
  - name: liyasthomas
  - name: AndrewBastin
dependencies:
  - name: common
    repository: https://homelab-ci.github.io/ezUxewsl
    version: 4.5.3
  - name: postgresql
    version: 11.6.12
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: Changed
      description: Updated service port to 80
    - kind: Added
      description: Initial application at 2023.12.2
