---
apiVersion: v2
appVersion: 2.0.1
description: Paperless - Index and archive all of your scanned paper documents
name: paperless
version: 9.1.7
kubeVersion: ">=1.16.0-0"
keywords:
  - paperless
home: https://github.com/homelab-ci/ezUxewsl/tree/master/charts/stable/paperless
icon: https://avatars.githubusercontent.com/u/47271576?s=200&v=4
sources:
  - https://github.com/paperless-ngx/paperless-ngx
maintainers:
  - name: mr-onion-2
  - name: jonnobrow
    email: jonathan@jonnobrow.co.uk
  - name: morremeyer
    email: charts@mor.re
dependencies:
  - name: common
    repository: https://homelab-ci.github.io/library-ezUxewsl
    version: 4.5.2
  - name: postgresql
    version: 11.6.12
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 16.13.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Bumped app version to 2.0.1
    - kind: changed
      description: Bumped app version to 2.0.0
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
