remote: origin
target-branch: master
helm-extra-args: --timeout 600s
chart-dirs:
  - charts/incubator
  - charts/stable
excluded-charts:
  - charts/incubator/kah-common-chart
  - charts/incubator/sdtd
  - charts/stable/alertmanager-bot
  - charts/stable/alertmanager-discord
  - charts/stable/amcrest2mqtt
  - charts/stable/facebox
  - charts/stable/factorio
  - charts/stable/foundryvtt
  - charts/stable/heimdall
  - charts/stable/multus
  - charts/stable/pod-gateway
  - charts/stable/promcord
  - charts/stable/reg
  - charts/stable/ser2sock
  - charts/stable/satisfactory
  - charts/stable/zalando-postgres-cluster
  - charts/stable/zigbee2mqtt
  - charts/stable/wireguard
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - homelab-ci-libraries=https://homelab-ci.github.io/library-ezUxewsl
  - homelab-ci=https://homelab-ci.github.io/ezUxewsl
  - jetstack=https://charts.jetstack.io
