remote: origin
target-branch: master
helm-extra-args: --timeout 600s
chart-dirs:
  - charts/incubator
  - charts/stable
excluded-charts:
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - homelab-ci-libraries=https://homelab-ci.github.io/library-ezUxewsl
  - homelab-ci=https://homelab-ci.github.io/ezUxewsl
  - jetstack=https://charts.jetstack.io
