{{/* Make sure all variables are set properly */}}
{{- include "common.values.setup" . }}

{{/* Append the hardcoded settings */}}
{{- define "whosatmyfeeder.harcodedValues" -}}
  {{/* Append the configMap volume to the volumes */}}
persistence:
  whosatmyfeeder-config:
    enabled: true
    type: "configMap"
    name: "{{ include "common.names.fullname" . }}-config"
    mountPath: "/config/config.yml"
    subPath: "config.yml"
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "whosatmyfeeder.harcodedValues" . | fromYaml) -}}

{{ include "common.all" . }}
