---
apiVersion: v2
appVersion: 0.0.138
description: scrypted helm package
name: scrypted
type: application
version: 0.3.7
kubeVersion: ">=1.16.0-0"
keywords:
  - scrypted
home: https://github.com/homelab-ci/ezUxewsl/tree/master/charts/stable/scrypted
icon: https://raw.githubusercontent.com/koush/scrypted/main/install/logo.png
sources:
  - https://github.com/koush/scrypted
maintainers:
  - name: scrypted
    email: koush@scrypted.com
dependencies:
  - name: common
    repository: https://homelab-ci.github.io/ezUxewsl
    version: 4.5.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Bumped app version to 0.3.4
    - kind: changed
      description: Bumped app version to 0.3.3
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
