apiVersion: v2
appVersion: 1.0.0
description: ${CHARTNAME} helm package
name: ${CHARTNAME}
version: 2.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - ${CHARTNAME}
home: https://homelab-ci.github.io/ezUxewsl/tree/master/charts/stable/${CHARTNAME}
icon: https://${CHARTNAME}.org/icon
sources:
  - https://github.com/${CHARTNAME}/${CHARTNAME}-docker
maintainers:
  - name: ${CHARTNAME}
    email: ${CHARTNAME}@${CHARTNAME}.com
dependencies:
  - name: common
    repository: https://homelab-ci.github.io/ezUxewsl
    version: 4.5.3
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial version
