---
apiVersion: v2
appVersion: 1.3.5
description: A minimalist, open source online pastebin running on an Nginx, php-fpm & Alpine Linux stack
name: privatebin
version: 2.1.4
kubeVersion: ">=1.16.0-0"
keywords:
  - privatebin
  - pastebin
home: https://github.com/homelab-ci/ezUxewsl/tree/master/charts/stable/privatebin
icon: https://privatebin.info/theme/img/icon.svg
sources:
  - https://github.com/PrivateBin/PrivateBin
  - https://github.com/PrivateBin/docker-nginx-fpm-alpine
maintainers:
  - name: psych0d0g
    email: psych0d0g@users.noreply.github.com
dependencies:
  - name: common
    repository: https://homelab-ci.github.io/library-ezUxewsl
    version: 4.5.2
  - name: postgresql
    version: 11.6.12
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Updated configmap to use `toRawJson` function to fix `&` being converted to unicode
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
