---
apiVersion: v2
appVersion: 4.1.0
description: Ryot - Roll your own tracker
name: ryot
version: 0.0.5
kubeVersion: ">=1.16.0-0"
keywords:
  - ryot
home: https://github.com/homelab-ci/ezUxewsl/tree/master/charts/stable/ryot
icon: https://raw.githubusercontent.com/IgnisDa/ryot/main/apps/frontend/public/icon-512x512.png
sources:
  - https://github.com/ignisda/ryot
maintainers:
  - name: IgnisDa
dependencies:
  - name: common
    repository: https://homelab-ci.github.io/ezUxewsl
    version: 0.0.1
  - name: postgresql
    version: 13.4.4
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Reset `common` chart dependency to version 0.0.1
    - kind: Changed
      description: Bumped application to 4.1.0
    - kind: Added
      description: Initial application at 4.0.0
